default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: sales_management_development

test:
  <<: *default
  database: sales_management_test

production:
  <<: *default
  database: sales_management_production
  username: postgres
  password: postgres